package interfaz.paresvistacontrol.opcionesempleadosinuso;

/**
 * Clase vista del area de un empleado que no tiene uso aun
 */
public class VistaOpcionesEmpleadoSinUso extends javax.swing.JFrame {

    CtrlVistaOpcionesEmpleadoSinUso control;

    /**
     * Creates new form VistaOpcionesPersonalDeOperativo
     */
    public VistaOpcionesEmpleadoSinUso() {
        initComponents();
        this.setLocationRelativeTo(null);
        control = new CtrlVistaOpcionesEmpleadoSinUso(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonConsultarDatosEnEmpresa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonSolicitarVacaciones = new javax.swing.JButton();
        botonConsultarEmergencias = new javax.swing.JButton();
        botonConsultarTurnos = new javax.swing.JButton();
        botonSolicitarCambioDeTurno = new javax.swing.JButton();
        mensajeErr = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonConsultarDatosEnEmpresa.setBackground(new java.awt.Color(153, 153, 255));
        botonConsultarDatosEnEmpresa.setText("Consultar mis datos personales");
        botonConsultarDatosEnEmpresa.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Area de Empleado sin USO");

        botonSolicitarVacaciones.setBackground(new java.awt.Color(153, 153, 255));
        botonSolicitarVacaciones.setText("Solicitar Vacaciones");
        botonSolicitarVacaciones.setEnabled(false);

        botonConsultarEmergencias.setBackground(new java.awt.Color(153, 153, 255));
        botonConsultarEmergencias.setText("Recursos humanos");
        botonConsultarEmergencias.setEnabled(false);

        botonConsultarTurnos.setBackground(new java.awt.Color(153, 153, 255));
        botonConsultarTurnos.setText("Consultar horarios");
        botonConsultarTurnos.setEnabled(false);

        botonSolicitarCambioDeTurno.setBackground(new java.awt.Color(255, 102, 102));
        botonSolicitarCambioDeTurno.setText("Salir");
        botonSolicitarCambioDeTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirAlLogin(evt);
            }
        });

        mensajeErr.setForeground(new java.awt.Color(255, 51, 51));
        mensajeErr.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(125, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonConsultarDatosEnEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonSolicitarVacaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonConsultarEmergencias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonConsultarTurnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonSolicitarCambioDeTurno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(136, Short.MAX_VALUE))
            .addComponent(mensajeErr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(botonConsultarDatosEnEmpresa)
                .addGap(18, 23, Short.MAX_VALUE)
                .addComponent(botonSolicitarVacaciones)
                .addGap(18, 23, Short.MAX_VALUE)
                .addComponent(botonConsultarEmergencias)
                .addGap(18, 23, Short.MAX_VALUE)
                .addComponent(botonConsultarTurnos)
                .addGap(18, 23, Short.MAX_VALUE)
                .addComponent(botonSolicitarCambioDeTurno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(mensajeErr, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonSalirAlLogin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirAlLogin
        control.procesaAccionSalirAlLogin();
    }//GEN-LAST:event_botonSalirAlLogin


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaOpcionesEmpleadoSinUso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaOpcionesEmpleadoSinUso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaOpcionesEmpleadoSinUso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaOpcionesEmpleadoSinUso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaOpcionesEmpleadoSinUso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConsultarDatosEnEmpresa;
    private javax.swing.JButton botonConsultarEmergencias;
    private javax.swing.JButton botonConsultarTurnos;
    private javax.swing.JButton botonSolicitarCambioDeTurno;
    private javax.swing.JButton botonSolicitarVacaciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel mensajeErr;
    // End of variables declaration//GEN-END:variables
}
