package interfaz.paresvistacontrol.opcionesoperador;



/**
 * Clase vista del MVC encargada de representar la vista para poder seleccionar las acciones del operador
 */
public class VistaOpcionesOperador extends javax.swing.JFrame {

    CtrlVistaOpcionesOperador control;

    /**
     * Creates new form VistaOpcionesPersonalDeOperativo
     */
    public VistaOpcionesOperador() {
        initComponents();
        this.setLocationRelativeTo(null);
        control = new CtrlVistaOpcionesOperador(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonConsultarDatosEnEmpresa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonOrganizarTurnosDeOperador = new javax.swing.JButton();
        botonSolicitarVacaciones = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonConsultarDatosEnEmpresa.setBackground(new java.awt.Color(153, 153, 255));
        botonConsultarDatosEnEmpresa.setText("Consultar datos personales");
        botonConsultarDatosEnEmpresa.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Arear operador");

        botonOrganizarTurnosDeOperador.setBackground(new java.awt.Color(102, 102, 255));
        botonOrganizarTurnosDeOperador.setText("Atender llamada");
        botonOrganizarTurnosDeOperador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtenderLlamadaEntrante(evt);
            }
        });

        botonSolicitarVacaciones.setBackground(new java.awt.Color(153, 153, 255));
        botonSolicitarVacaciones.setText("Ver turnos");
        botonSolicitarVacaciones.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(botonConsultarDatosEnEmpresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonSolicitarVacaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(botonOrganizarTurnosDeOperador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 43, Short.MAX_VALUE)
                .addComponent(botonConsultarDatosEnEmpresa)
                .addGap(18, 43, Short.MAX_VALUE)
                .addComponent(botonSolicitarVacaciones)
                .addGap(18, 43, Short.MAX_VALUE)
                .addComponent(botonOrganizarTurnosDeOperador)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAtenderLlamadaEntrante(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtenderLlamadaEntrante
        control.procesaAtenderLlamadaEntrante();
    }//GEN-LAST:event_botonAtenderLlamadaEntrante



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaOpcionesOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaOpcionesOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaOpcionesOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaOpcionesOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaOpcionesOperador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConsultarDatosEnEmpresa;
    private javax.swing.JButton botonOrganizarTurnosDeOperador;
    private javax.swing.JButton botonSolicitarVacaciones;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
